/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.AsteriskFileModel;
import util.AsteriskManager;
import util.SystemDate;

/**
 *
 * @author judah
 */
public class MainWindow extends javax.swing.JFrame {

    private String info[];
    private String currentPath;
    private String previousFileContent;
    private AsteriskFileModel currentFile;
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Configuration files", "conf", "conf~");

    /**
     * Creates new form mainWindow
     */
    public MainWindow() {
        initComponents();
        jLabelFileName.setVisible(false);
        jComboBoxPart.setVisible(false);
        jButtonAddPart.setVisible(false);
        jButtonEditPart.setVisible(false);
        jButtonRemovePart.setVisible(false);
        jScrollPane1.setVisible(false);
        jTableVariable.setVisible(false);
        jButtonAddVariable.setVisible(false);
        jButtonEditVariable.setVisible(false);
        jButtonRemoveVariable.setVisible(false);
        jComboBoxItens.setVisible(false);
        jTextAreaCom.setVisible(false);
        jScrollPane2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Open = new javax.swing.JFrame();
        jFileChooserOpen = new javax.swing.JFileChooser();
        Save = new javax.swing.JFrame();
        jFileChooserSave = new javax.swing.JFileChooser();
        jDialogGetPassword = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonPasswordOk = new javax.swing.JButton();
        jButtonPasswordCancel = new javax.swing.JButton();
        jDialogAddPart = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPartName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPartTag = new javax.swing.JTextField();
        jButtonOkAddPart = new javax.swing.JButton();
        jButtonCancelAddPart = new javax.swing.JButton();
        jDialogEditPart = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPartName1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPartTag1 = new javax.swing.JTextField();
        jButtonOkEditPart = new javax.swing.JButton();
        jButtonCancelEditPart = new javax.swing.JButton();
        jDialogAddVariable = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldVariable = new javax.swing.JTextField();
        jTextFieldValue = new javax.swing.JTextField();
        jButtonOkAddVariable = new javax.swing.JButton();
        jButtonCancelAddVariable = new javax.swing.JButton();
        jDialogEditVariable = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldVariable1 = new javax.swing.JTextField();
        jTextFieldValue1 = new javax.swing.JTextField();
        jButtonOkEditVariable = new javax.swing.JButton();
        jButtonCancelEditVariable = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelFileName = new javax.swing.JLabel();
        jComboBoxPart = new javax.swing.JComboBox();
        jButtonAddPart = new javax.swing.JButton();
        jButtonEditPart = new javax.swing.JButton();
        jButtonRemovePart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVariable = new javax.swing.JTable();
        jButtonAddVariable = new javax.swing.JButton();
        jButtonEditVariable = new javax.swing.JButton();
        jButtonRemoveVariable = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxCommand = new javax.swing.JComboBox();
        jComboBoxItens = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaCom = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemUpdate = new javax.swing.JMenuItem();

        jFileChooserOpen.setCurrentDirectory(new java.io.File("/etc/asterisk"));
        jFileChooserOpen.setFileFilter(filter);
        jFileChooserOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OpenLayout = new javax.swing.GroupLayout(Open.getContentPane());
        Open.getContentPane().setLayout(OpenLayout);
        OpenLayout.setHorizontalGroup(
            OpenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OpenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jFileChooserOpen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        OpenLayout.setVerticalGroup(
            OpenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpenLayout.createSequentialGroup()
                .addComponent(jFileChooserOpen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jFileChooserSave.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooserSave.setFileFilter(filter);
        jFileChooserSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SaveLayout = new javax.swing.GroupLayout(Save.getContentPane());
        Save.getContentPane().setLayout(SaveLayout);
        SaveLayout.setHorizontalGroup(
            SaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaveLayout.createSequentialGroup()
                .addComponent(jFileChooserSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SaveLayout.setVerticalGroup(
            SaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaveLayout.createSequentialGroup()
                .addComponent(jFileChooserSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDialogGetPassword.setTitle("Authentication required!");

        jLabel1.setText("Root password:");

        jPasswordField1.setText("541236987");

        jButtonPasswordOk.setText("Ok");
        jButtonPasswordOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPasswordOkActionPerformed(evt);
            }
        });

        jButtonPasswordCancel.setText("Cancel");
        jButtonPasswordCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPasswordCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogGetPasswordLayout = new javax.swing.GroupLayout(jDialogGetPassword.getContentPane());
        jDialogGetPassword.getContentPane().setLayout(jDialogGetPasswordLayout);
        jDialogGetPasswordLayout.setHorizontalGroup(
            jDialogGetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogGetPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogGetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogGetPasswordLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                    .addGroup(jDialogGetPasswordLayout.createSequentialGroup()
                        .addComponent(jButtonPasswordOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPasswordCancel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialogGetPasswordLayout.setVerticalGroup(
            jDialogGetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogGetPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogGetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogGetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPasswordOk)
                    .addComponent(jButtonPasswordCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Session:");

        jLabel3.setText("Advanced:");

        jLabel4.setText("Tag:");

        jButtonOkAddPart.setText("Ok");
        jButtonOkAddPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkAddPartActionPerformed(evt);
            }
        });

        jButtonCancelAddPart.setText("Cancel");
        jButtonCancelAddPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelAddPartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogAddPartLayout = new javax.swing.GroupLayout(jDialogAddPart.getContentPane());
        jDialogAddPart.getContentPane().setLayout(jDialogAddPartLayout);
        jDialogAddPartLayout.setHorizontalGroup(
            jDialogAddPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddPartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogAddPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogAddPartLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPartTag))
                    .addGroup(jDialogAddPartLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPartName))
                    .addGroup(jDialogAddPartLayout.createSequentialGroup()
                        .addGroup(jDialogAddPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jDialogAddPartLayout.createSequentialGroup()
                                .addComponent(jButtonOkAddPart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancelAddPart)))
                        .addGap(0, 209, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialogAddPartLayout.setVerticalGroup(
            jDialogAddPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddPartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogAddPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPartName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogAddPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPartTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogAddPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOkAddPart)
                    .addComponent(jButtonCancelAddPart))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Session:");

        jLabel6.setText("Advanced:");

        jLabel7.setText("Tag:");

        jButtonOkEditPart.setText("Ok");
        jButtonOkEditPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkEditPartActionPerformed(evt);
            }
        });

        jButtonCancelEditPart.setText("Cancel");
        jButtonCancelEditPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelEditPartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogEditPartLayout = new javax.swing.GroupLayout(jDialogEditPart.getContentPane());
        jDialogEditPart.getContentPane().setLayout(jDialogEditPartLayout);
        jDialogEditPartLayout.setHorizontalGroup(
            jDialogEditPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditPartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogEditPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogEditPartLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPartTag1))
                    .addGroup(jDialogEditPartLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPartName1))
                    .addGroup(jDialogEditPartLayout.createSequentialGroup()
                        .addGroup(jDialogEditPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jDialogEditPartLayout.createSequentialGroup()
                                .addComponent(jButtonOkEditPart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancelEditPart)))
                        .addGap(0, 209, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialogEditPartLayout.setVerticalGroup(
            jDialogEditPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditPartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogEditPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPartName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogEditPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldPartTag1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogEditPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOkEditPart)
                    .addComponent(jButtonCancelEditPart))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("Variable:");

        jLabel9.setText("Value:");

        jButtonOkAddVariable.setText("Ok");
        jButtonOkAddVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkAddVariableActionPerformed(evt);
            }
        });

        jButtonCancelAddVariable.setText("Cancel");
        jButtonCancelAddVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelAddVariableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogAddVariableLayout = new javax.swing.GroupLayout(jDialogAddVariable.getContentPane());
        jDialogAddVariable.getContentPane().setLayout(jDialogAddVariableLayout);
        jDialogAddVariableLayout.setHorizontalGroup(
            jDialogAddVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddVariableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogAddVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogAddVariableLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldVariable))
                    .addGroup(jDialogAddVariableLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValue))
                    .addGroup(jDialogAddVariableLayout.createSequentialGroup()
                        .addComponent(jButtonOkAddVariable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelAddVariable)
                        .addGap(0, 177, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialogAddVariableLayout.setVerticalGroup(
            jDialogAddVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddVariableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogAddVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogAddVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogAddVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOkAddVariable)
                    .addComponent(jButtonCancelAddVariable))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setText("Variable:");

        jLabel11.setText("Value:");

        jButtonOkEditVariable.setText("Ok");
        jButtonOkEditVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkEditVariableActionPerformed(evt);
            }
        });

        jButtonCancelEditVariable.setText("Cancel");
        jButtonCancelEditVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelEditVariableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogEditVariableLayout = new javax.swing.GroupLayout(jDialogEditVariable.getContentPane());
        jDialogEditVariable.getContentPane().setLayout(jDialogEditVariableLayout);
        jDialogEditVariableLayout.setHorizontalGroup(
            jDialogEditVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditVariableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogEditVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogEditVariableLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldVariable1))
                    .addGroup(jDialogEditVariableLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValue1))
                    .addGroup(jDialogEditVariableLayout.createSequentialGroup()
                        .addComponent(jButtonOkEditVariable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelEditVariable)
                        .addGap(0, 177, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialogEditVariableLayout.setVerticalGroup(
            jDialogEditVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditVariableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogEditVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldVariable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogEditVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogEditVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOkEditVariable)
                    .addComponent(jButtonCancelEditVariable))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelFileName.setText("File:");

        jComboBoxPart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPartActionPerformed(evt);
            }
        });

        jButtonAddPart.setText("Add");
        jButtonAddPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPartActionPerformed(evt);
            }
        });

        jButtonEditPart.setText("Edit");
        jButtonEditPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditPartActionPerformed(evt);
            }
        });

        jButtonRemovePart.setText("Remove");
        jButtonRemovePart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemovePartActionPerformed(evt);
            }
        });

        jTableVariable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Variable", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableVariable);

        jButtonAddVariable.setText("Add");
        jButtonAddVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddVariableActionPerformed(evt);
            }
        });

        jButtonEditVariable.setText("Edit");
        jButtonEditVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditVariableActionPerformed(evt);
            }
        });

        jButtonRemoveVariable.setText("Remove");
        jButtonRemoveVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveVariableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jComboBoxPart, 0, 230, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonAddPart)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonEditPart)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonRemovePart))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelFileName)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonAddVariable)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonEditVariable)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonRemoveVariable)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelFileName)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAddPart)
                        .addComponent(jButtonRemovePart)
                        .addComponent(jButtonEditPart))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAddVariable)
                        .addComponent(jButtonEditVariable)
                        .addComponent(jButtonRemoveVariable))
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Config.", jPanel1);

        jComboBoxCommand.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select","Agents", "IAX", "SIP", "Queues" }));
        jComboBoxCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCommandActionPerformed(evt);
            }
        });

        jComboBoxItens.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxItensActionPerformed(evt);
            }
        });

        jTextAreaCom.setColumns(20);
        jTextAreaCom.setRows(5);
        jScrollPane2.setViewportView(jTextAreaCom);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jComboBoxItens, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBoxCommand, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxCommand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Management", jPanel2);

        jMenuFile.setText("File");

        jMenuItemOpen.setText("Open");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemOpen);

        jMenuItemSave.setText("Save");
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSave);

        jMenuItemUpdate.setText("Update");
        jMenuItemUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUpdateActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemUpdate);

        jMenuBar1.add(jMenuFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooserSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooserSaveActionPerformed

    private void jFileChooserOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooserOpenActionPerformed

    private void getPermission(String absolutePath) throws IOException {
        this.currentPath = absolutePath;
        jDialogGetPassword.setModal(true);
        jDialogGetPassword.setSize(300, 100);
        jDialogGetPassword.setVisible(true);
    }

    private void readFile(File file) throws FileNotFoundException, IOException {
        try (BufferedReader in = new BufferedReader(new FileReader(file))) {
            String str = "";
            previousFileContent = "";
            while (in.ready()) {
                String a = in.readLine();
                previousFileContent += a + "\n";

                if (a.contains(";")) {
                    if (a.startsWith(";")) {
                        a = "";
                    } else {
                        a = a.split(";")[0].trim() + "";
                    }
                } else {
                    a = a.trim();
                }

                if ((!a.isEmpty()) && (!"".equals(a))) {
                    str += "" + a + "\n";
                }
            }
            currentFile = new AsteriskFileModel(file.getName(), file.getAbsolutePath(), str);
            initEditor();
        } catch (IOException ex) {
            try {
                getPermission(file.getAbsolutePath());
                readFile(file);
            } catch (IOException ex1) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }

    private void openEditor() {
        jLabelFileName.setVisible(true);
        jComboBoxPart.setVisible(true);
        jButtonAddPart.setVisible(true);
        jButtonEditPart.setVisible(true);
        jButtonRemovePart.setVisible(true);
        jScrollPane1.setVisible(true);
        jTableVariable.setVisible(true);
        jButtonAddVariable.setVisible(true);
        jButtonEditVariable.setVisible(true);
        jButtonRemoveVariable.setVisible(true);
    }

    private void initEditor() {
        jLabelFileName.setText(currentFile.getName().substring(0, currentFile.getName().indexOf(".conf")) + ":");

        updateJComboBoxPart();
        updateJTableVariable();
        openEditor();
    }

    private void updateJComboBoxPart() {
        String[] stringArray = new String[currentFile.getSessionList().size()];
        for (int i = 0; i < stringArray.length; i++) {
            stringArray[i] = currentFile.getSession(i).toString();
        }
        jComboBoxPart.setModel(new javax.swing.DefaultComboBoxModel(stringArray));
        updateJTableVariable();
    }

    private void updateJTableVariable() {
        String[][] stringMatrix = new String[(currentFile.getSession(jComboBoxPart.getSelectedIndex()).getVariableList().size())][2];

        for (int i = 0; i < currentFile.getSession(jComboBoxPart.getSelectedIndex()).getVariableList().size(); i++) {
            stringMatrix[i][0] = currentFile.getSession(jComboBoxPart.getSelectedIndex()).getVariable(i).getName();
            stringMatrix[i][1] = currentFile.getSession(jComboBoxPart.getSelectedIndex()).getVariable(i).getValue();


        }

        jTableVariable.setModel(new javax.swing.table.DefaultTableModel(
                stringMatrix,
                new String[]{
                    "Variable", "Value"
                }) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableVariable);
    }

    private void openFile() {
        int value = jFileChooserOpen.showOpenDialog(this);
        if (value == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooserOpen.getSelectedFile();
            try {
                readFile(file);
            } catch (IOException ex) {
                try {
                    getPermission(file.getAbsolutePath());
                    readFile(file);


                } catch (IOException ex1) {
                    Logger.getLogger(MainWindow.class
                            .getName()).log(Level.SEVERE, null, ex1);
                }
//                ex.printStackTrace();
            }
        }
    }

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
        openFile();
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void refreshAsterisk() {
        try {
            AsteriskManager asteriskManager = new AsteriskManager();
            asteriskManager.login();
            asteriskManager.refresh();
            asteriskManager.disconnect();
        } catch (UnknownHostException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void saveFile(File file) throws IOException {
        try (BufferedWriter out = new BufferedWriter(new FileWriter(file))) {
            String[] split = previousFileContent.split("\n");
            String fileContent = "";
            for (int i = 0; i < split.length; i++) {
                if (!split[i].isEmpty()) {
                    if (split[i].charAt(0) == ';') {
                        fileContent += split[i] + "\n";
                    } else {
                        fileContent += ";" + split[i] + "\n";
                    }
                }
            }
            SystemDate date = new SystemDate();
            fileContent += ";Generated by AsteriskTools  at " + date.getDateTime() + "\n\n";
            fileContent += currentFile;
            out.write(fileContent);
            System.out.println("REFRESH");
            refreshAsterisk();
            System.out.println("Generated by AsteriskTools  at " + date.getDateTime() + "\n\n");
        } catch (IOException ex) {
            try {
                getPermission(file.getAbsolutePath());
                saveFile(file);


            } catch (IOException ex1) {
                Logger.getLogger(MainWindow.class
                        .getName()).log(Level.SEVERE, null, ex1);
            }
            ex.printStackTrace();
        }

    }

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed
        if (currentFile != null) {
            int value = jFileChooserSave.showSaveDialog(this);
            if (value == JFileChooser.APPROVE_OPTION) {
                File file = jFileChooserSave.getSelectedFile();
                try {
                    saveFile(file);
                } catch (IOException ex) {
                    try {
                        getPermission(file.getAbsolutePath());
                        saveFile(file);


                    } catch (IOException ex1) {
                        Logger.getLogger(MainWindow.class
                                .getName()).log(Level.SEVERE, null, ex1);
                    }
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jMenuItemSaveActionPerformed

    private void updateAsteriskFile() {
        if (currentFile != null) {
            File file = new File(currentFile.getPath());
            try {
                saveFile(file);
            } catch (IOException ex) {
                try {
                    getPermission(file.getAbsolutePath());
                    saveFile(file);


                } catch (IOException ex1) {
                    Logger.getLogger(MainWindow.class
                            .getName()).log(Level.SEVERE, null, ex1);
                }
            }
        }
    }

    private void jMenuItemUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUpdateActionPerformed
        updateAsteriskFile();
    }//GEN-LAST:event_jMenuItemUpdateActionPerformed

    private void jComboBoxPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPartActionPerformed
        updateJTableVariable();
    }//GEN-LAST:event_jComboBoxPartActionPerformed

    private void jButtonRemoveVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveVariableActionPerformed
        currentFile.getSession(jComboBoxPart.getSelectedIndex()).removeVariable(jTableVariable.getSelectedRow());
        updateJTableVariable();
    }//GEN-LAST:event_jButtonRemoveVariableActionPerformed

    private void jButtonRemovePartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemovePartActionPerformed
        currentFile.removeSession(jComboBoxPart.getSelectedIndex());
        updateJComboBoxPart();
    }//GEN-LAST:event_jButtonRemovePartActionPerformed

    private void jButtonPasswordOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPasswordOkActionPerformed
        try {
            Runtime run = Runtime.getRuntime();
            String string = new String(jPasswordField1.getPassword());
            System.out.println("echo " + string + " | sudo -S chmod 777 " + this.currentPath + "");
            run.exec("echo " + string + " | sudo -S chmod 777 " + this.currentPath + "\r\n\r\n\r\n\r\n");
            jDialogGetPassword.dispose();


        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPasswordOkActionPerformed

    private void jButtonPasswordCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPasswordCancelActionPerformed
        jDialogGetPassword.dispose();
    }//GEN-LAST:event_jButtonPasswordCancelActionPerformed

    private void jButtonAddPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPartActionPerformed
        jDialogAddPart.setModal(true);
        jDialogAddPart.setSize(300, 160);
        jDialogAddPart.setVisible(true);
    }//GEN-LAST:event_jButtonAddPartActionPerformed

    private void jButtonOkAddPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkAddPartActionPerformed
        if (!jTextFieldPartName.getText().isEmpty()) {
            currentFile.addSession(jTextFieldPartName.getText(), jTextFieldPartTag.getText());
            updateJComboBoxPart();
            jDialogAddPart.dispose();
        }
    }//GEN-LAST:event_jButtonOkAddPartActionPerformed

    private void jButtonCancelAddPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelAddPartActionPerformed
        jDialogAddPart.dispose();
    }//GEN-LAST:event_jButtonCancelAddPartActionPerformed

    private void jButtonOkEditPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkEditPartActionPerformed
        if (!jTextFieldPartName1.getText().isEmpty()) {
            currentFile.getSession(jComboBoxPart.getSelectedIndex()).setName(jTextFieldPartName1.getText());
            currentFile.getSession(jComboBoxPart.getSelectedIndex()).setInfo(jTextFieldPartTag1.getText());
            updateJComboBoxPart();
            jDialogEditPart.dispose();
        }
    }//GEN-LAST:event_jButtonOkEditPartActionPerformed

    private void jButtonCancelEditPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelEditPartActionPerformed
        jDialogEditPart.dispose();
    }//GEN-LAST:event_jButtonCancelEditPartActionPerformed

    private void jButtonEditPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPartActionPerformed
        jTextFieldPartName1.setText(currentFile.getSession(jComboBoxPart.getSelectedIndex()).getName());
        jTextFieldPartTag1.setText(currentFile.getSession(jComboBoxPart.getSelectedIndex()).getInfo());
        jDialogEditPart.setModal(true);
        jDialogEditPart.setSize(300, 160);
        jDialogEditPart.setVisible(true);
    }//GEN-LAST:event_jButtonEditPartActionPerformed

    private void jButtonAddVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddVariableActionPerformed
        jDialogAddVariable.setModal(true);
        jDialogAddVariable.setSize(300, 160);
        jDialogAddVariable.setVisible(true);
    }//GEN-LAST:event_jButtonAddVariableActionPerformed

    private void jButtonOkAddVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkAddVariableActionPerformed
        if (!jTextFieldVariable.getText().isEmpty()) {
            currentFile.getSession((jComboBoxPart.getSelectedIndex())).addVariable(jTextFieldVariable.getText(), jTextFieldValue.getText());
            updateJComboBoxPart();
            jDialogAddVariable.dispose();
        }
    }//GEN-LAST:event_jButtonOkAddVariableActionPerformed

    private void jButtonCancelAddVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelAddVariableActionPerformed
        jDialogAddVariable.dispose();
    }//GEN-LAST:event_jButtonCancelAddVariableActionPerformed

    private void jButtonEditVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditVariableActionPerformed
        if (jTableVariable.getSelectedRow() > -1) {
            jTextFieldVariable1.setText(currentFile.getSession(jComboBoxPart.getSelectedIndex()).getVariable(jTableVariable.getSelectedRow()).getName());
            jTextFieldValue1.setText(currentFile.getSession(jComboBoxPart.getSelectedIndex()).getVariable(jTableVariable.getSelectedRow()).getValue());
            jDialogEditVariable.setModal(true);
            jDialogEditVariable.setSize(300, 160);
            jDialogEditVariable.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditVariableActionPerformed

    private void jButtonOkEditVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkEditVariableActionPerformed
        if (!jTextFieldVariable1.getText().isEmpty()) {
            currentFile.getSession((jComboBoxPart.getSelectedIndex())).getVariable(jTableVariable.getSelectedRow()).setName(jTextFieldVariable1.getText());
            currentFile.getSession((jComboBoxPart.getSelectedIndex())).getVariable(jTableVariable.getSelectedRow()).setValue(jTextFieldValue1.getText());
            updateJComboBoxPart();
            jDialogEditVariable.dispose();
        }
    }//GEN-LAST:event_jButtonOkEditVariableActionPerformed

    private void jButtonCancelEditVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelEditVariableActionPerformed
        jDialogEditVariable.dispose();
    }//GEN-LAST:event_jButtonCancelEditVariableActionPerformed

    private void jComboBoxCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCommandActionPerformed
        System.out.println("Index:" + jComboBoxCommand.getSelectedIndex());
        if (jComboBoxCommand.getSelectedIndex() > 0) {
            try {
                jComboBoxItens.setVisible(true);
                AsteriskManager manager = new AsteriskManager();
                manager.login();
                switch (jComboBoxCommand.getSelectedIndex()) {
                    case 1:
                        manager.Agents();

                        break;

                    case 2:
                        manager.IAXpeers();
                        
                        break;

                    case 3:
                        manager.SIPpeers();
                        
                        break;

                    case 4:
                        try {
                            manager.Queues();
                        } catch (InterruptedException ex) {
                            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        break;
                }
                String name[] = new String[manager.nameList.size() + 1];
                info = new String[manager.nameList.size() + 1];
                name[0] = "Select";
                for (int i = 0; i < manager.nameList.size(); i++) {
                    name[i + 1] = manager.nameList.get(i);
                    info[i + 1] = manager.infoList.get(i);
                }
                jComboBoxItens.setModel(new javax.swing.DefaultComboBoxModel(name));
                manager.disconnect();
                System.out.println("TRUE");
            } catch (IOException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jComboBoxItens.setVisible(false);
        }
    }//GEN-LAST:event_jComboBoxCommandActionPerformed

    private void jComboBoxItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxItensActionPerformed
        if (jComboBoxItens.getSelectedIndex() > -1) {
            jScrollPane2.setVisible(true);
            jTextAreaCom.setVisible(true);
            jTextAreaCom.setText(info[jComboBoxItens.getSelectedIndex()]);
        } else {
            jTextAreaCom.setVisible(false);
            jScrollPane2.setVisible(false);
        }
    }//GEN-LAST:event_jComboBoxItensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());


        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Open;
    private javax.swing.JFrame Save;
    private javax.swing.JButton jButtonAddPart;
    private javax.swing.JButton jButtonAddVariable;
    private javax.swing.JButton jButtonCancelAddPart;
    private javax.swing.JButton jButtonCancelAddVariable;
    private javax.swing.JButton jButtonCancelEditPart;
    private javax.swing.JButton jButtonCancelEditVariable;
    private javax.swing.JButton jButtonEditPart;
    private javax.swing.JButton jButtonEditVariable;
    private javax.swing.JButton jButtonOkAddPart;
    private javax.swing.JButton jButtonOkAddVariable;
    private javax.swing.JButton jButtonOkEditPart;
    private javax.swing.JButton jButtonOkEditVariable;
    private javax.swing.JButton jButtonPasswordCancel;
    private javax.swing.JButton jButtonPasswordOk;
    private javax.swing.JButton jButtonRemovePart;
    private javax.swing.JButton jButtonRemoveVariable;
    private javax.swing.JComboBox jComboBoxCommand;
    private javax.swing.JComboBox jComboBoxItens;
    private javax.swing.JComboBox jComboBoxPart;
    private javax.swing.JDialog jDialogAddPart;
    private javax.swing.JDialog jDialogAddVariable;
    private javax.swing.JDialog jDialogEditPart;
    private javax.swing.JDialog jDialogEditVariable;
    private javax.swing.JDialog jDialogGetPassword;
    private javax.swing.JFileChooser jFileChooserOpen;
    private javax.swing.JFileChooser jFileChooserSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFileName;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenuItem jMenuItemUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableVariable;
    private javax.swing.JTextArea jTextAreaCom;
    private javax.swing.JTextField jTextFieldPartName;
    private javax.swing.JTextField jTextFieldPartName1;
    private javax.swing.JTextField jTextFieldPartTag;
    private javax.swing.JTextField jTextFieldPartTag1;
    private javax.swing.JTextField jTextFieldValue;
    private javax.swing.JTextField jTextFieldValue1;
    private javax.swing.JTextField jTextFieldVariable;
    private javax.swing.JTextField jTextFieldVariable1;
    // End of variables declaration//GEN-END:variables
}
